class equipment{
  List rows = [
    {
      "name": 'Baret',
      "code": '1111111111',
      "type": 'Protective',
      "weight": '0.421',
      "size": 'M',
      "color": 'Yellow',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": '3M"',
      "id": '1',
    },
    {
      "name": 'Tirmanis Ip',
      "code": '1111111112',
      "type": 'Light',
      "weight": '0.1',
      "size": '2MMx10M',
      "color": 'Blue',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": 'SIMOND',
      "id": '2',
    },
    {
      "name": 'Cadir',
      "code": '1111111113',
      "type": 'Sheltering',
      "weight": '2.450',
      "size": 'L',
      "color": 'Black',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'nylon',
      "amount": '25',
      "tradeMark": 'Quechua',
      "id": '3',
    },
    {
      "name": 'Baret',
      "code": '1111111111',
      "type": 'Protective',
      "weight": '0.421',
      "size": 'M',
      "color": 'Yellow',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": '3M"',
      "id": '1',
    },
    {
      "name": 'Tirmanis Ip',
      "code": '1111111112',
      "type": 'Light',
      "weight": '0.1',
      "size": '2MMx10M',
      "color": 'Blue',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": 'SIMOND',
      "id": '2',
    },
    {
      "name": 'Cadir',
      "code": '1111111113',
      "type": 'Sheltering',
      "weight": '2.450',
      "size": 'L',
      "color": 'Black',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'nylon',
      "amount": '25',
      "tradeMark": 'Quechua',
      "id": '3',
    },    {
      "name": 'Baret',
      "code": '1111111111',
      "type": 'Protective',
      "weight": '0.421',
      "size": 'M',
      "color": 'Yellow',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": '3M"',
      "id": '1',
    },
    {
      "name": 'Tirmanis Ip',
      "code": '1111111112',
      "type": 'Light',
      "weight": '0.1',
      "size": '2MMx10M',
      "color": 'Blue',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": 'SIMOND',
      "id": '2',
    },
    {
      "name": 'Cadir',
      "code": '1111111113',
      "type": 'Sheltering',
      "weight": '2.450',
      "size": 'L',
      "color": 'Black',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'nylon',
      "amount": '25',
      "tradeMark": 'Quechua',
      "id": '3',
    },    {
      "name": 'Baret',
      "code": '1111111111',
      "type": 'Protective',
      "weight": '0.421',
      "size": 'M',
      "color": 'Yellow',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": '3M"',
      "id": '1',
    },
    {
      "name": 'Tirmanis Ip',
      "code": '1111111112',
      "type": 'Light',
      "weight": '0.1',
      "size": '2MMx10M',
      "color": 'Blue',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": 'SIMOND',
      "id": '2',
    },
    {
      "name": 'Cadir',
      "code": '1111111113',
      "type": 'Sheltering',
      "weight": '2.450',
      "size": 'L',
      "color": 'Black',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'nylon',
      "amount": '25',
      "tradeMark": 'Quechua',
      "id": '3',
    },    {
      "name": 'Baret',
      "code": '1111111111',
      "type": 'Protective',
      "weight": '0.421',
      "size": 'M',
      "color": 'Yellow',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": '3M"',
      "id": '1',
    },
    {
      "name": 'Tirmanis Ip',
      "code": '1111111112',
      "type": 'Light',
      "weight": '0.1',
      "size": '2MMx10M',
      "color": 'Blue',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": 'SIMOND',
      "id": '2',
    },
    {
      "name": 'Cadir',
      "code": '1111111113',
      "type": 'Sheltering',
      "weight": '2.450',
      "size": 'L',
      "color": 'Black',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'nylon',
      "amount": '25',
      "tradeMark": 'Quechua',
      "id": '3',
    },    {
      "name": 'Baret',
      "code": '1111111111',
      "type": 'Protective',
      "weight": '0.421',
      "size": 'M',
      "color": 'Yellow',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": '3M"',
      "id": '1',
    },
    {
      "name": 'Tirmanis Ip',
      "code": '1111111112',
      "type": 'Light',
      "weight": '0.1',
      "size": '2MMx10M',
      "color": 'Blue',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": 'SIMOND',
      "id": '2',
    },
    {
      "name": 'Cadir',
      "code": '1111111113',
      "type": 'Sheltering',
      "weight": '2.450',
      "size": 'L',
      "color": 'Black',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'nylon',
      "amount": '25',
      "tradeMark": 'Quechua',
      "id": '3',
    },    {
      "name": 'Baret',
      "code": '1111111111',
      "type": 'Protective',
      "weight": '0.421',
      "size": 'M',
      "color": 'Yellow',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": '3M"',
      "id": '1',
    },
    {
      "name": 'Tirmanis Ip',
      "code": '1111111112',
      "type": 'Light',
      "weight": '0.1',
      "size": '2MMx10M',
      "color": 'Blue',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": 'SIMOND',
      "id": '2',
    },
    {
      "name": 'Cadir',
      "code": '1111111113',
      "type": 'Sheltering',
      "weight": '2.450',
      "size": 'L',
      "color": 'Black',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'nylon',
      "amount": '25',
      "tradeMark": 'Quechua',
      "id": '3',
    },    {
      "name": 'Baret',
      "code": '1111111111',
      "type": 'Protective',
      "weight": '0.421',
      "size": 'M',
      "color": 'Yellow',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": '3M"',
      "id": '1',
    },
    {
      "name": 'Tirmanis Ip',
      "code": '1111111112',
      "type": 'Light',
      "weight": '0.1',
      "size": '2MMx10M',
      "color": 'Blue',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": 'SIMOND',
      "id": '2',
    },
    {
      "name": 'Cadir',
      "code": '1111111113',
      "type": 'Sheltering',
      "weight": '2.450',
      "size": 'L',
      "color": 'Black',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'nylon',
      "amount": '25',
      "tradeMark": 'Quechua',
      "id": '3',
    },    {
      "name": 'Baret',
      "code": '1111111111',
      "type": 'Protective',
      "weight": '0.421',
      "size": 'M',
      "color": 'Yellow',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": '3M"',
      "id": '1',
    },
    {
      "name": 'Tirmanis Ip',
      "code": '1111111112',
      "type": 'Light',
      "weight": '0.1',
      "size": '2MMx10M',
      "color": 'Blue',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'Plastic',
      "amount": '45',
      "tradeMark": 'SIMOND',
      "id": '2',
    },
    {
      "name": 'Cadir',
      "code": '1111111113',
      "type": 'Sheltering',
      "weight": '2.450',
      "size": 'L',
      "color": 'Black',
      "buyingTime": '10/10/2020',
      "usingStatus": 'Used',
      "previusCountDate": '00/00/0000',
      "lastCountDate": '11/11/1111',
      "kind": 'nylon',
      "amount": '25',
      "tradeMark": 'Quechua',
      "id": '3',
    },
  ];
  List cols = [
    {"title": 'Name', 'widthFactor': 0.3, 'key': 'name'},
    {"title": 'Code', 'widthFactor': 0.3, 'key': 'code'},
    {"title": 'Type', 'widthFactor': 0.3, 'key': 'type'},
    {"title": 'Weight','widthFactor': 0.3, 'key': 'weight'},
    {"title": 'Size', 'widthFactor': 0.3,'key': 'size'},
    {"title": 'Color', 'widthFactor': 0.3, 'key': 'color'},
    {"title": 'Buying Time', 'widthFactor': 0.4, 'key': 'buyingTime'},
    {"title": 'Using Status','widthFactor': 0.3, 'key': 'usingStatus'},
    {"title": 'Previus Count Date', 'widthFactor': 0.4, 'key': 'lastCountDate'},
    {"title": 'Last Count Date', 'widthFactor': 0.4, 'key': 'lastCountDate'},
    {"title": 'Kind', 'widthFactor': 0.3, 'key': 'kind'},
    {"title": 'Amount','widthFactor': 0.3, 'key': 'amount'},
    {"title": 'Trademark', 'widthFactor': 0.3, 'key': 'tradeMark'},
    {"title": 'Id','widthFactor': 0.3, 'key': 'id'},
  ];
}